#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "90deef511c8f4d38a7c6e617c00d15e2" }
]

[assets]
directory = "./public"
